// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Terminal.Data.Context;

#nullable disable

namespace Terminal.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260225032820_AddResourceCodeTable")]
    partial class AddResourceCodeTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Terminal.Core.DbEntities.ResourceCode", b =>
                {
                    b.Property<int>("FuelCodeKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionKey")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResourceKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceName")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ResourcePrice")
                        .HasColumnType("TEXT");

                    b.HasKey("FuelCodeKey");

                    b.ToTable("resource_code", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
