// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Terminal.Persistence.ParamDB;

#nullable disable

namespace Terminal.Persistence.ParamDB.Migrations
{
    [DbContext(typeof(ParamDbContext))]
    partial class ParamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Terminal.Core.ParamDbEntities.Param", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("param", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
