<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Terminal.Core\Terminal.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Mono.Android">
        <HintPath>..\..\..\..\..\..\Program Files\dotnet\packs\Microsoft.Android.Ref.36\36.1.30\ref\net10.0\Mono.Android.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MessageBox.Avalonia" />
      <PackageReference Include="MessageBox.Avalonia.Markdown" />
      <PackageReference Include="Microsoft.Extensions.Hosting" />
      <PackageReference Include="Microsoft.Extensions.Http" />
      <PackageReference Include="System.IO.Ports" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="Xmls\*.xml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
