// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Terminal.Persistence.EventDB;

#nullable disable

namespace Terminal.Persistence.EventDB.Migrations
{
    [DbContext(typeof(EventDbContext))]
    [Migration("20260514055715_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Terminal.Core.DbEntities.EventDb.Incass", b =>
                {
                    b.Property<int>("IncassKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastDatetimeEnd")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime?>("LastDatetimeStart")
                        .HasColumnType("DATETIME");

                    b.HasKey("IncassKey");

                    b.ToTable("incass", (string)null);
                });

            modelBuilder.Entity("Terminal.Core.DbEntities.EventDb.ProtocolFilingForm", b =>
                {
                    b.Property<int>("ProtokolFillingFormKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CurrentObjectParameterValue")
                        .HasColumnType("DOUBLE");

                    b.Property<int?>("ErrorCode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EventDatetime")
                        .HasColumnType("DATETIME");

                    b.Property<string>("EventInfo")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EventKey")
                        .HasColumnType("NUMERIC(20)");

                    b.Property<double?>("EventValue")
                        .HasColumnType("DOUBLE");

                    b.Property<string>("Hash")
                        .HasColumnType("varchar(50)");

                    b.Property<double?>("LatestObjectParameterValue")
                        .HasColumnType("DOUBLE");

                    b.Property<int?>("LogCode")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ObjectId")
                        .HasColumnType("NUMERIC(20)")
                        .HasColumnName("ObjectID");

                    b.Property<int?>("ObjectType")
                        .HasColumnType("NUMERIC(20)");

                    b.Property<long?>("PlaceId")
                        .HasColumnType("NUMERIC(20)")
                        .HasColumnName("PlaceID");

                    b.Property<int?>("SncProjectKey")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sncProjectKey");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("NUMERIC(20)")
                        .HasColumnName("SubjectID");

                    b.Property<int?>("SubjectType")
                        .HasColumnType("NUMERIC(20)");

                    b.HasKey("ProtokolFillingFormKey");

                    b.ToTable("ProtocolFilingForm", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
