// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Terminal.Persistence.MainDB;

#nullable disable

namespace Terminal.Persistence.MainDB.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260729094652_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Terminal.Core.Entities.DbEntities.MainDb.Allow", b =>
                {
                    b.Property<int>("AllowKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IssuerKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestServer")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<int?>("ShopKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("AllowKey");

                    b.ToTable("allow", (string)null);
                });

            modelBuilder.Entity("Terminal.Core.Entities.DbEntities.MainDb.BonusChange", b =>
                {
                    b.Property<int>("BonusChangeShopKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ApplicationID");

                    b.Property<decimal?>("BonusChange1")
                        .HasColumnType("NUMERIC( 20, 3 )")
                        .HasColumnName("BonusChange");

                    b.Property<int?>("CheckNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommodityGuid")
                        .HasColumnType("VARCHAR( 255 )");

                    b.Property<decimal?>("ElectronicNumber")
                        .HasColumnType("NUMERIC( 20 )");

                    b.Property<int?>("ErrorCode")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("GraphicalNumber")
                        .HasColumnType("NUMERIC( 20 )");

                    b.Property<int?>("IssuerCardId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IssuerCardID");

                    b.Property<int?>("IssuerTerminalId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IssuerTerminalID");

                    b.Property<int?>("OrganisationKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PersonKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SetOfGoodsGuid")
                        .HasColumnType("VARCHAR( 255 )");

                    b.Property<int?>("ShiftKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShopKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShoppingCartKey")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TerminalKey")
                        .HasColumnType("NUMERIC( 14 )");

                    b.Property<DateTime?>("TransactionDatetime")
                        .HasColumnType("DATETIME");

                    b.HasKey("BonusChangeShopKey");

                    b.HasIndex(new[] { "SetOfGoodsGuid" }, "BonChange1")
                        .IsUnique();

                    b.ToTable("bonus_change", (string)null);
                });

            modelBuilder.Entity("Terminal.Core.Entities.DbEntities.MainDb.CardPassword", b =>
                {
                    b.Property<int>("CardPasswordKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ElectronicNumber")
                        .HasColumnType("NUMERIC( 20 )");

                    b.Property<long?>("GraphicalNumber")
                        .HasColumnType("NUMERIC( 20 )");

                    b.Property<long?>("GraphicalNumberUpos")
                        .HasColumnType("NUMERIC( 20 )")
                        .HasColumnName("GraphicalNumberUPOS");

                    b.Property<long?>("LastSessionEnd")
                        .HasColumnType("BIGINT");

                    b.Property<long?>("LastSessionStart")
                        .HasColumnType("BIGINT");

                    b.Property<int?>("Password")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SaleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("CardPasswordKey");

                    b.ToTable("card_password", (string)null);
                });

            modelBuilder.Entity("Terminal.Core.Entities.DbEntities.MainDb.CardUpdate", b =>
                {
                    b.Property<int>("CardUpdateKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AfterValue")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<int?>("ApplicationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("ApplicationType")
                        .HasColumnType("TINYINT");

                    b.Property<string>("BeforeValue")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<byte?>("CorrectionType")
                        .HasColumnType("TINYINT");

                    b.Property<long?>("ElectronicNumber")
                        .HasColumnType("BIGINT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime?>("EnterDate")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ErrorCode")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsSent")
                        .HasColumnType("BOOLEAN");

                    b.Property<int?>("IssuerCardKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IssuerKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrganisationKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OwnerKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParameterAddValue")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("ParameterRepValue")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<byte?>("ParameterType")
                        .HasColumnType("TINYINT");

                    b.Property<byte?>("ResultCode")
                        .HasColumnType("TINYINT");

                    b.Property<int?>("ShiftKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShiftTerminalKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShopKey")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("DATETIME");

                    b.Property<decimal?>("TerminalKey")
                        .HasColumnType("NUMERIC( 14 )");

                    b.Property<int?>("TransactionKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TransactionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("DATETIME");

                    b.HasKey("CardUpdateKey");

                    b.ToTable("card_update", (string)null);
                });

            modelBuilder.Entity("Terminal.Core.Entities.DbEntities.MainDb.Correction", b =>
                {
                    b.Property<int>("CorrectionsKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApplicationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("ApplicationType")
                        .HasColumnType("TINYINT");

                    b.Property<byte?>("CorrectionType")
                        .HasColumnType("TINYINT");

                    b.Property<long?>("ElectronicNumber")
                        .HasColumnType("BIGINT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime?>("EnterDate")
                        .HasColumnType("DATETIME");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("BOOL");

                    b.Property<int?>("IssuerKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<int?>("OrganisationKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OwnerKey")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ParameterAddValue")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("ParameterRepValue")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<byte?>("ParameterType")
                        .HasColumnType("TINYINT");

                    b.Property<int?>("ShopKey")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("TransactionKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TransactionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("CorrectionsKey");

                    b.ToTable("corrections", (string)null);
                });

            modelBuilder.Entity("Terminal.Core.Entities.DbEntities.MainDb.Dispenser", b =>
                {
                    b.Property<int>("DispenserShopKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BeginBalance")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<decimal?>("BeginBalanceCalculation")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<decimal?>("BeginTemperature")
                        .HasColumnType("NUMERIC( 10, 4 )");

                    b.Property<decimal?>("EndBalance")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<decimal?>("EndBalanceCalculation")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<decimal?>("EndTemperature")
                        .HasColumnType("NUMERIC( 10, 4 )");

                    b.Property<int?>("ErrorCode")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Flags")
                        .HasColumnType("BIGINT");

                    b.Property<int?>("ResourceKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResourceShopKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShiftKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShopKey")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TerminalKey")
                        .HasColumnType("NUMERIC( 14 )");

                    b.Property<int?>("VendorKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VendorName")
                        .HasColumnType("VARCHAR(10)");

                    b.HasKey("DispenserShopKey");

                    b.HasIndex(new[] { "VendorKey", "ShiftKey", "TerminalKey" }, "BalVender1")
                        .IsUnique();

                    b.ToTable("dispenser", (string)null);
                });

            modelBuilder.Entity("Terminal.Core.Entities.DbEntities.MainDb.Event", b =>
                {
                    b.Property<int>("EventsKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("EventInfo")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<int?>("EventObject")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventResult")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TerminalKey")
                        .HasColumnType("NUMERIC( 14 )");

                    b.HasKey("EventsKey");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Terminal.Core.Entities.DbEntities.MainDb.IssuerFuelTable", b =>
                {
                    b.Property<int>("IssuerFuelCodeKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("IsCard")
                        .HasColumnType("TINYINT");

                    b.Property<int?>("IssuerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IssuerID");

                    b.Property<int?>("ResourceKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResourceShopKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("IssuerFuelCodeKey");

                    b.ToTable("issuer_fuel_table", (string)null);
                });

            modelBuilder.Entity("Terminal.Core.Entities.DbEntities.MainDb.ListOrg", b =>
                {
                    b.Property<int>("ListOrgKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrganisationKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrganisationName")
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("ListOrgKey");

                    b.ToTable("list_org", (string)null);
                });

            modelBuilder.Entity("Terminal.Core.Entities.DbEntities.MainDb.ListOwner", b =>
                {
                    b.Property<int>("ListOwnerKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GraphicalNumber")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<int?>("OrganisationKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OwnerKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerName")
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("ListOwnerKey");

                    b.ToTable("list_owner", (string)null);
                });

            modelBuilder.Entity("Terminal.Core.Entities.DbEntities.MainDb.Payment", b =>
                {
                    b.Property<int>("PaymentShopKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AppStatus")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AppValue")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ApplicationID");

                    b.Property<int?>("CollectionKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommonApplicationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CommonApplicationID");

                    b.Property<long?>("ElectronicNumber")
                        .HasColumnType("BIGINT");

                    b.Property<int?>("ErrorCode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("GraphicalNumber")
                        .HasColumnType("NUMERIC( 20 )");

                    b.Property<string>("Guid")
                        .HasColumnType("VARCHAR(35)");

                    b.Property<bool?>("IsSent")
                        .HasColumnType("BOOLEAN");

                    b.Property<int?>("IssuerCardKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IssuerKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nz")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("NZ");

                    b.Property<int?>("OrganisationKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OwnerKey")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("DATETIME");

                    b.Property<decimal?>("PaymentSum")
                        .HasColumnType("NUMERIC(20,3)");

                    b.Property<decimal?>("PaymentVolume")
                        .HasColumnType("NUMERIC(20,3)");

                    b.Property<int?>("ResourceKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShiftKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShiftTerminalKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShopKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShoppingCartKey")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TerminalKey")
                        .HasColumnType("NUMERIC( 14 )");

                    b.HasKey("PaymentShopKey");

                    b.HasIndex(new[] { "Guid" }, "PaymentIndex")
                        .IsUnique();

                    b.ToTable("payment", (string)null);
                });

            modelBuilder.Entity("Terminal.Core.Entities.DbEntities.MainDb.PosUpdate", b =>
                {
                    b.Property<int>("PosUpdateShopKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AfterValue")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<byte?>("AppStatus")
                        .HasColumnType("TINYINT");

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ApplicationID");

                    b.Property<string>("BeforeValue")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("ChangeValue")
                        .HasColumnType("VARCHAR(35)");

                    b.Property<int?>("CheckNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CollectionKey")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ElectronicNumber")
                        .HasColumnType("BIGINT");

                    b.Property<int?>("ErrorCode")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("GraphicalNumber")
                        .HasColumnType("BIGINT");

                    b.Property<string>("Guid")
                        .HasColumnType("VARCHAR(35)");

                    b.Property<bool?>("IsSent")
                        .HasColumnType("BOOLEAN");

                    b.Property<int?>("IssuerCardKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IssuerKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrganisationKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OwnerKey")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PosUpdateDate")
                        .HasColumnType("DATETIME");

                    b.Property<byte?>("PosUpdateType")
                        .HasColumnType("TINYINT");

                    b.Property<int?>("ResourceKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShiftKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShiftTerminalKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShopKey")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TerminalKey")
                        .HasColumnType("NUMERIC( 14 )");

                    b.HasKey("PosUpdateShopKey");

                    b.HasIndex(new[] { "Guid" }, "PosUpdateIndex")
                        .IsUnique();

                    b.ToTable("pos_update", (string)null);
                });

            modelBuilder.Entity("Terminal.Core.Entities.DbEntities.MainDb.Prohibition", b =>
                {
                    b.Property<int>("ProhibitionKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BeginDate")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("IssuerKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrganisationKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OwnerKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShopKey")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("Sign")
                        .HasColumnType("TINYINT");

                    b.HasKey("ProhibitionKey");

                    b.ToTable("prohibition", (string)null);
                });

            modelBuilder.Entity("Terminal.Core.Entities.DbEntities.MainDb.Repayment", b =>
                {
                    b.Property<int>("RepaymentShopKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ApplicationID");

                    b.Property<byte?>("CardType")
                        .HasColumnType("TINYINT");

                    b.Property<long?>("ElectronicNumber")
                        .HasColumnType("BIGINT");

                    b.Property<int?>("ErrorCode")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsSent")
                        .HasColumnType("BOOLEAN");

                    b.Property<int?>("IssuerCardKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IssuerKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrganisationKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OwnerKey")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RepaymentDate")
                        .HasColumnType("DATETIME");

                    b.Property<byte?>("RepaymentType")
                        .HasColumnType("TINYINT");

                    b.Property<double?>("RepaymentValue")
                        .HasColumnType("NUMERIC(20,3)");

                    b.Property<int?>("ShiftKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShiftTerminalKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShopKey")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TerminalKey")
                        .HasColumnType("NUMERIC( 14 )");

                    b.HasKey("RepaymentShopKey");

                    b.ToTable("repayment", (string)null);
                });

            modelBuilder.Entity("Terminal.Core.Entities.DbEntities.MainDb.Request", b =>
                {
                    b.Property<int>("VendorKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BaseType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CompleteVolume")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<int?>("DerivedType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndOfFilling")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("InitialVolume")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<decimal?>("LastVolume")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<int?>("RequestType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResourceKey")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ShopCost")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<int?>("ShoppingCartKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("VendorKey");

                    b.ToTable("request", (string)null);
                });

            modelBuilder.Entity("Terminal.Core.Entities.DbEntities.MainDb.ResourceCode", b =>
                {
                    b.Property<int>("FuelCodeKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CollectionKey")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Density")
                        .HasColumnType("NUMERIC( 20, 4 )");

                    b.Property<byte?>("IsShow")
                        .HasColumnType("TINYINT");

                    b.Property<int>("ResourceKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceName")
                        .HasColumnType("VARCHAR( 50 )");

                    b.Property<decimal?>("ResourcePrice")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<int?>("Temperature")
                        .HasColumnType("NUMERIC( 20, 4 )");

                    b.HasKey("FuelCodeKey");

                    b.HasIndex(new[] { "CollectionKey", "ResourceKey" }, "ResourceUnique")
                        .IsUnique();

                    b.ToTable("resource_code", (string)null);
                });

            modelBuilder.Entity("Terminal.Core.Entities.DbEntities.MainDb.Selling", b =>
                {
                    b.Property<int>("TransactionShopKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<float?>("AppLimit")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<int?>("AppMode")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("AppSecondLimit")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<double?>("AppSecondValue")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<int?>("AppStatus")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("AppValue")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ApplicationID");

                    b.Property<decimal?>("BasePrice")
                        .HasColumnType("NUMERIC( 10, 3 )");

                    b.Property<int?>("BaseType")
                        .HasColumnType("INTEGER( 1 )");

                    b.Property<float?>("BeginTemperature")
                        .HasColumnType("NUMERIC( 10, 4 )");

                    b.Property<decimal?>("BonusIn")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<decimal?>("BonusInCost")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<decimal?>("BonusOut")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<decimal?>("BonusOutCost")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<int?>("CardType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CheckNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ClientCost")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<int?>("CollectionKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommodityGuid")
                        .HasColumnType("VARCHAR( 255 )");

                    b.Property<int?>("CommodityKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommonApplicationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CommonApplicationID");

                    b.Property<int?>("DelayedBonusType")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Density")
                        .HasColumnType("NUMERIC( 10, 4 )");

                    b.Property<int?>("DerivedType")
                        .HasColumnType("INTEGER( 1 )");

                    b.Property<long?>("ElectronicNumber")
                        .HasColumnType("NUMERIC( 20 )");

                    b.Property<float?>("EndTemperature")
                        .HasColumnType("NUMERIC( 10, 4 )");

                    b.Property<int?>("ErrorCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalCode")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<double?>("GraphicalNumber")
                        .HasColumnType("NUMERIC( 20 )");

                    b.Property<string>("Guid")
                        .HasColumnType("VARCHAR(35)");

                    b.Property<int?>("IsAccountRep")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IssuerCardId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IssuerCardID");

                    b.Property<int?>("IssuerTerminalId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IssuerTerminalID");

                    b.Property<int?>("OrganisationKey")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Overflow")
                        .HasColumnType("NUMERIC( 10, 4 )");

                    b.Property<decimal?>("ParcelPrice")
                        .HasColumnType("NUMERIC( 10, 3 )");

                    b.Property<int?>("PaymentOfCommodityKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PersonKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RequestFlags")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("RequestedAmount")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<decimal?>("RequestedCost")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<int?>("ResourceCode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResourceKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceName")
                        .HasColumnType("VARCHAR( 50 )");

                    b.Property<int?>("ResourceShopKey")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SellingFlags")
                        .HasColumnType("BIGINT");

                    b.Property<decimal?>("SellingPrice")
                        .HasColumnType("NUMERIC( 10, 3 )");

                    b.Property<string>("SetOfGoodsGuid")
                        .HasColumnType("VARCHAR( 255 )");

                    b.Property<int?>("SetOfGoodsKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShiftKey")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ShopBaseCost")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<decimal?>("ShopCost")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<int?>("ShopKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShoppingCartKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sign")
                        .HasColumnType("VARCHAR( 255 )");

                    b.Property<float?>("Temperature")
                        .HasColumnType("NUMERIC( 10, 4 )");

                    b.Property<long?>("TerminalKey")
                        .HasColumnType("NUMERIC( 14 )");

                    b.Property<int?>("TransactionCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TransactionDatetime")
                        .HasColumnType("DATETIME");

                    b.Property<long?>("ValidityPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VendorKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransactionShopKey");

                    b.HasIndex(new[] { "Guid" }, "TrTer")
                        .IsUnique();

                    b.ToTable("selling", (string)null);
                });

            modelBuilder.Entity("Terminal.Core.Entities.DbEntities.MainDb.SellingCoupon", b =>
                {
                    b.Property<int>("SellingCouponShopKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BaseType")
                        .HasColumnType("INTEGER (1)");

                    b.Property<int?>("CollectionKey")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CommodityGuid")
                        .HasColumnType("VARCHAR (255)");

                    b.Property<int?>("CouponType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DerivedType")
                        .HasColumnType("INTEGER (1)");

                    b.Property<long?>("ElectronicNumber")
                        .HasColumnType("BIGINT");

                    b.Property<int?>("ErrorCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GraphicalNumber")
                        .HasColumnType("VARCHAR (250)");

                    b.Property<int?>("OrganisationKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PersonKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResourceKey")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SetOfGoodsGuid")
                        .HasColumnType("VARCHAR (255)");

                    b.Property<int?>("ShiftKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShopKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShoppingCartKey")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TerminalKey")
                        .HasColumnType("NUMERIC (14)");

                    b.Property<DateTime?>("TransactionDatetime")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("UsedVolume")
                        .HasColumnType("NUMERIC (20, 3)");

                    b.HasKey("SellingCouponShopKey");

                    b.ToTable("sellingcoupon", (string)null);
                });

            modelBuilder.Entity("Terminal.Core.Entities.DbEntities.MainDb.SellingIgnore", b =>
                {
                    b.Property<int>("TransactionShopKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<decimal?>("AppLimit")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<int?>("AppMode")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AppSecondLimit")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<decimal?>("AppSecondValue")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<int?>("AppStatus")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AppValue")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ApplicationID");

                    b.Property<decimal?>("BasePrice")
                        .HasColumnType("NUMERIC( 10, 3 )");

                    b.Property<int?>("BaseType")
                        .HasColumnType("INTEGER( 1 )");

                    b.Property<decimal?>("BeginTemperature")
                        .HasColumnType("NUMERIC( 10, 4 )");

                    b.Property<decimal?>("BonusIn")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<decimal?>("BonusInCost")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<decimal?>("BonusOut")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<decimal?>("BonusOutCost")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<int?>("CardType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CheckNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ClientCost")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<int?>("CollectionKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommodityGuid")
                        .HasColumnType("VARCHAR( 255 )");

                    b.Property<int?>("CommodityKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommonApplicationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CommonApplicationID");

                    b.Property<int?>("DelayedBonusType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Density")
                        .HasColumnType("NUMERIC( 10, 4 )");

                    b.Property<int?>("DerivedType")
                        .HasColumnType("INTEGER( 1 )");

                    b.Property<decimal?>("ElectronicNumber")
                        .HasColumnType("NUMERIC( 20 )");

                    b.Property<decimal?>("EndTemperature")
                        .HasColumnType("NUMERIC( 10, 4 )");

                    b.Property<int?>("ErrorCode")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("GraphicalNumber")
                        .HasColumnType("NUMERIC( 20 )");

                    b.Property<string>("Guid")
                        .HasColumnType("VARCHAR(35)");

                    b.Property<int?>("IsAccountRep")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IssuerCardId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IssuerCardID");

                    b.Property<int?>("IssuerTerminalId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IssuerTerminalID");

                    b.Property<int?>("OrganisationKey")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Overflow")
                        .HasColumnType("NUMERIC( 10, 4 )");

                    b.Property<decimal?>("ParcelPrice")
                        .HasColumnType("NUMERIC( 10, 3 )");

                    b.Property<int?>("PaymentOfCommodityKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PersonKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RequestFlags")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("RequestedAmount")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<decimal?>("RequestedCost")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<int?>("ResourceCode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResourceKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceName")
                        .HasColumnType("VARCHAR( 50 )");

                    b.Property<int?>("ResourceShopKey")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SellingFlags")
                        .HasColumnType("BIGINT");

                    b.Property<decimal?>("SellingPrice")
                        .HasColumnType("NUMERIC( 10, 3 )");

                    b.Property<string>("SetOfGoodsGuid")
                        .HasColumnType("VARCHAR( 255 )");

                    b.Property<int?>("SetOfGoodsKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShiftKey")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ShopBaseCost")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<decimal?>("ShopCost")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<int?>("ShopKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShoppingCartKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sign")
                        .HasColumnType("VARCHAR( 255 )");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("NUMERIC( 10, 4 )");

                    b.Property<decimal?>("TerminalKey")
                        .HasColumnType("NUMERIC( 14 )");

                    b.Property<int?>("TransactionCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TransactionDatetime")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ValidityPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VendorKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransactionShopKey");

                    b.ToTable("selling_ignore", (string)null);
                });

            modelBuilder.Entity("Terminal.Core.Entities.DbEntities.MainDb.Setting", b =>
                {
                    b.Property<int>("SettingsKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("SettingsKey");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("Terminal.Core.Entities.DbEntities.MainDb.Shift", b =>
                {
                    b.Property<int>("ShiftShopKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ErrorCode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HttpRecv")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HttpSend")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsOpened")
                        .HasColumnType("BOOLEAN");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ShiftDate")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ShiftKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShopKey")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TerminalKey")
                        .HasColumnType("NUMERIC( 14 )");

                    b.HasKey("ShiftShopKey");

                    b.ToTable("shift", (string)null);
                });

            modelBuilder.Entity("Terminal.Core.Entities.DbEntities.MainDb.TransferCard", b =>
                {
                    b.Property<int>("TransferCardKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AppLimit")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<int?>("AppMode")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AppSecondLimit")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<decimal?>("AppSecondValue")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<int?>("AppStatus")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AppValue")
                        .HasColumnType("NUMERIC( 20, 3 )");

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ApplicationID");

                    b.Property<int?>("CollectionKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommonApplicationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CommonApplicationID");

                    b.Property<decimal?>("ElectronicNumber")
                        .HasColumnType("NUMERIC( 20 )");

                    b.Property<decimal?>("GraphicalNumber")
                        .HasColumnType("NUMERIC( 20 )");

                    b.Property<int?>("IssuerCardId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IssuerCardID");

                    b.Property<int?>("OrganisationKey")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrganisationListOrgKey")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ParcelPrice")
                        .HasColumnType("NUMERIC( 10, 3 )");

                    b.Property<int?>("PersonKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResourceCode")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ValidityPeriod")
                        .HasColumnType("BIGINT");

                    b.HasKey("TransferCardKey");

                    b.HasIndex("OrganisationListOrgKey");

                    b.ToTable("transfer_card", (string)null);
                });

            modelBuilder.Entity("Terminal.Core.Entities.DbEntities.MainDb.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CardNumber")
                        .HasColumnType("NUMERIC( 16 )");

                    b.Property<decimal?>("EcardNumber")
                        .HasColumnType("NUMERIC( 16 )")
                        .HasColumnName("ECardNumber");

                    b.Property<int?>("IssuerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR( 50 )");

                    b.Property<int?>("OrganisationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TerminalKey")
                        .HasColumnType("NUMERIC( 14 )");

                    b.Property<string>("UserPassword")
                        .HasColumnType("VARCHAR( 35 )");

                    b.Property<int?>("UserType")
                        .HasColumnType("NUMERIC( 2 )");

                    b.HasKey("UserId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Terminal.Core.Entities.Models.SalesReportResult", b =>
                {
                    b.Property<decimal?>("A")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AR")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ARA")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ICI")
                        .HasColumnType("INTEGER");

                    b.Property<string>("N")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OK")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PT")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("SBC")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SBCR")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SBCRA")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SC")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SCR")
                        .HasColumnType("TEXT");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Terminal.Core.Entities.DbEntities.MainDb.TransferCard", b =>
                {
                    b.HasOne("Terminal.Core.Entities.DbEntities.MainDb.ListOrg", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationListOrgKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Terminal.Core.Entities.DbEntities.MainDb.User", b =>
                {
                    b.HasOne("Terminal.Core.Entities.DbEntities.MainDb.ListOrg", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId");

                    b.Navigation("Organisation");
                });
#pragma warning restore 612, 618
        }
    }
}
