<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentAssertions" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
      <PackageReference Include="Microsoft.NET.Test.Sdk" />
      <PackageReference Include="Moq" />
      <PackageReference Include="NUnit" />
      <PackageReference Include="NUnit3TestAdapter" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Terminal.Application\Terminal.Application.csproj" />
      <ProjectReference Include="..\Terminal\Terminal.csproj" />
    </ItemGroup>

</Project>
